
spring:
  application:
    name: user-service
  config:
    # import: optional:configserver:http://localhost:8888


#  datasource:
#    url: jdbc:postgresql://localhost:5432/fitness_user_db
#    username: postgres
#    password: Vishal@07
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: localhost