#spring.application.name=AiService
#server:
#  port: 8083

spring:
  application:
    name: AI-SERVICE
  config:
      import: optional:configserver:http://localhost:8888

#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/fitness-recommendation
#      database: fitness-recommendation
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#gemini:
#  api:
#    url: ${GEMINI_API_URL}
#    key: ${GEMINI_API_KEY}
#
#rabbitmq:
#  exchange:
#    name: fitness.exchange
#  queue:
#    name: activity.queue
#  routing:
#    key: activity.tracking
#
